//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IMandelbrotService")]
public interface IMandelbrotService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMandelbrotService/GenerateMandelbrotRow", ReplyAction="http://tempuri.org/IMandelbrotService/GenerateMandelbrotRowResponse")]
    int[] GenerateMandelbrotRow(double yp, double y, double x, double size, int pixels);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IMandelbrotService/GenerateMandelbrotRow", ReplyAction="http://tempuri.org/IMandelbrotService/GenerateMandelbrotRowResponse")]
    System.IAsyncResult BeginGenerateMandelbrotRow(double yp, double y, double x, double size, int pixels, System.AsyncCallback callback, object asyncState);
    
    int[] EndGenerateMandelbrotRow(System.IAsyncResult result);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IMandelbrotServiceChannel : IMandelbrotService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class MandelbrotServiceClient : System.ServiceModel.ClientBase<IMandelbrotService>, IMandelbrotService
{
    
    public MandelbrotServiceClient()
    {
    }
    
    public MandelbrotServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public MandelbrotServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public MandelbrotServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public MandelbrotServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public int[] GenerateMandelbrotRow(double yp, double y, double x, double size, int pixels)
    {
        return base.Channel.GenerateMandelbrotRow(yp, y, x, size, pixels);
    }
    
    public System.IAsyncResult BeginGenerateMandelbrotRow(double yp, double y, double x, double size, int pixels, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGenerateMandelbrotRow(yp, y, x, size, pixels, callback, asyncState);
    }
    
    public int[] EndGenerateMandelbrotRow(System.IAsyncResult result)
    {
        return base.Channel.EndGenerateMandelbrotRow(result);
    }
}
